# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - siniwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sinilab-gddng5g8gyc3ckde.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bac3bd8b256b4df8a6d2237782a217df }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0f2221e89ce461fa75de58ec6d9bf31 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sinilab-gddng5g8gyc3ckde.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bac3bd8b256b4df8a6d2237782a217df }}/ohjtoimlab4:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'siniwebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a61e01a32514f9bbc7f4949e2907467 }}
        images: 'sinilab-gddng5g8gyc3ckde.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bac3bd8b256b4df8a6d2237782a217df }}/ohjtoimlab4:${{ github.sha }}'